version: '3'

vars:
  LIBEXT: '{{if eq OS "windows"}}dll{{else if eq OS "darwin"}}dylib{{else}}so{{end}}'
  build: '{{default "Release" .build}}'
  root: '{{default "." .root}}'
  msys2_path: '{{default (print .root "/third_party/msys2") .msys2_path}}'
  yarn_path: .yarn/releases/yarn-2.4.0.cjs
  yarn: 'node {{.yarn_path}}'

includes:
  os: ./Taskfile_{{if eq OS "windows"}}win{{else}}unix{{end}}.yml

tasks:
  default:
    cmds:
      - task -l

  build-tool:
    desc: Build our build tool
    dir: packages/build-tools
    sources:
      - '**/*.go'
      - ../libknossos/pkg/archives/*.go
    cmds:
      - go build -o ../../.tools/tool{{exeExt}}

  install-tools:
    desc: Installs necessary go tools in the workspace (task, pggen, protoc plugins, ...)
    sources:
      - packages/build-tools/tools.go
    cmds:
      - task: build-tool
      - tool install-tools

  # Only run "yarn install" if necessary
  js-deps:
    sources:
      - package.json
      - yarn.lock
    cmds:
      - '{{.yarn}} install'

  fetch-deps:
    desc: Automatically downloads dependencies not covered by install-tools
    cmds:
      - task: build-tool
      - tool fetch-deps
      - task: js-deps

  bootstrap-mingw64:
    desc: Runs first-time setup for MSYS2 (Windows-only)
    dir: '{{.msys2_path}}'
    status:
      - test -f mingw64/bin/gcc.exe
    cmds:
      - task: fetch-deps
      - usr/bin/bash --login -c "pacman -Syuu --noconfirm"
      - usr/bin/bash --login -c "pacman -Syuu --noconfirm"
      - usr/bin/bash --login -c "pacman -Su --noconfirm --needed mingw-w64-x86_64-gcc"

  proto-build:
    desc: Generates TS and Go bindings from the .proto API definitions
    sources:
      - packages/api/definitions/*.proto
    vars:
      mv: '{{if eq OS "windows"}}tool mv{{else}}mv{{end}}'
      rm: '{{if eq OS "windows"}}tool rm -r{{else}}rm -r{{end}}'
    cmds:
      - task: fetch-deps
      - task: install-tools
      - protoc -Ipackages/api/definitions client.proto --go_out=packages/api/client --go_opt=paths=source_relative --twirp_out=packages/api/twirp
      - protoc -Ipackages/api/definitions service.proto --go_out=packages/api/api --go_opt=paths=source_relative --twirp_out=packages/api/twirp
      # twirp doesn't support go.mod paths so we have to move the generated files to the correct location
      - '{{.mv}} packages/api/twirp/github.com/ngld/knossos/packages/api/api/*.go packages/api/api'
      - '{{.mv}} packages/api/twirp/github.com/ngld/knossos/packages/api/client/*.go packages/api/client'
      - '{{.rm}} packages/api/twirp/github.com'
      - '{{.yarn}} protoc google/protobuf/timestamp.proto --ts_out=packages/api/api'
      - '{{.yarn}} protoc -Ipackages/api/definitions client.proto --ts_out=packages/api/api'
      - '{{.yarn}} protoc -Ipackages/api/definitions service.proto --ts_out=packages/api/api'

  server-build:
    desc: Compiles the Nebula server code
    dir: packages/server
    sources:
      - cmd/**/*.go
      - pkg/**/*.go
    generates:
      - ../../build/nebula
    cmds:
      - task: proto-build
      - go generate -x ./pkg/db/queries.go
      - go build -o ../../build/nebula{{exeExt}} ./cmd/server/main.go

  front-watch:
    desc: Automatically recompiles Nebula frontend code on change
    cmds:
      - task: front-css
      - '{{.yarn}} front:watch'

  front-css:
    desc: Compiles Tailwind CSS for Nebula (only rarely necessary)
    dir: packages/front
    sources:
      - src/tw-index.css
      - tailwind.config.js
    generates:
      - gen/tw-index.css
    cmds:
      - 'node ../../{{.yarn_path}} postcss src/tw-index.css -o gen/tw-index.css'

  front-build:
    desc: Builds the assets for Nebula's frontend
    dir: packages/front
    sources:
      - src/**/*.ts
      - src/**/*.tsx
      - src/**/*.js
      - src/**/*.css
    generates:
      - dist/**/*
    cmds:
      - NODE_ENV=production node ../../{{.yarn_path}} postcss src/tw-index.css -o gen/tw-index.css
      - 'node ../../{{.yarn_path}} webpack --env production --color --progress'

  client-ui-watch:
    desc: Automatically recompiles Knossos UI code on change
    cmds:
      - task: client-ui-css
      - '{{.yarn}} client:watch'

  client-ui-css:
    desc: Compiles Tailwind CSS for Knossos (only rarely necessary)
    dir: packages/client-ui
    sources:
      - src/tw-index.css
      - tailwind.config.js
    cmds:
      - 'node ../../{{.yarn_path}} postcss src/tw-index.css -o gen/tw-index.css'

  client-ui-build:
    desc: Builds the assets for Nebula's client-uiend
    dir: packages/client-ui
    sources:
      - src/**/*.ts
      - src/**/*.tsx
      - src/**/*.js
      - src/**/*.css
    generates:
      - dist/**/*
    vars:
      res_dir: '{{if eq OS "darwin"}}knossos.app/Contents/Frameworks/Chromium Embedded Framework.framework/Resources/{{end}}'
    cmds:
      - task: build-tool
      - NODE_ENV=production node ../../{{.yarn_path}} postcss src/tw-index.css -o gen/tw-index.css
      - 'node ../../{{.yarn_path}} webpack --env production --color --progress'
      - tool pack-kar "../../build/client/launcher/{{.build}}/{{.res_dir}}ui.kar" dist/prod

  libarchive-build:
    desc: Builds libarchive with CMake (uses MSYS2 on Windows)
    sources:
      - third_party/libarchive/src/**/*.{c,h}
    cmds:
      - task: '{{if eq OS "windows"}}bootstrap-mingw64{{else}}fetch-deps{{end}}'
      - task: os:libarchive-build
        vars:
          msys2_path: '{{.msys2_path}}'
          root: '{{.root}}'

  libknossos-build:
    desc: Builds libknossos (client-side, non-UI logic)
    dir: packages/libknossos
    sources:
      - ../../.tools/tool{{exeExt}}
      - '**/*.go'
      - ../libarchive/**/*.go
    vars:
      OUTPATH: ../../build/libknossos/libknossos.{{.LIBEXT}}
      windows_ldflags: '{{print .msys2_path "/mingw64/lib/libiconv.a" | fromSlash}} {{print .msys2_path "/mingw64/lib/libcharset.a" | fromSlash}} {{print .msys2_path "/mingw64/lib/libz.a" | fromSlash}} {{print .msys2_path "/mingw64/lib/liblzma.a" | fromSlash}} {{print .msys2_path "/mingw64/lib/libzstd.a" | fromSlash}}'
    env:
      CGO_LDFLAGS: '{{if eq OS "windows"}}{{.windows_ldflags}}{{end}}'
    cmds:
      - task: build-tool
      - task: libarchive-build
      - task: proto-build
      - go build -x -o {{.OUTPATH}} -buildmode c-shared ./api
      - tool gen-dyn-loader ../../build/libknossos/libknossos.h ../../build/libknossos/dynknossos.h

  client-build:
    desc: Builds the Knossos client
    vars:
      generator: '{{default "Unix Makefiles" .generator}}'
    cmds:
      - task: libarchive-build
      - task: libknossos-build
      - if [ ! -d build/client ]; then tool mkdir -p build/client; fi
      - cd build/client && cmake -G"{{.generator}}" -DCMAKE_BUILD_TYPE={{.build}} -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ../../packages/client
      - cd build/client && {{if eq .generator "Ninja"}}ninja{{else}}make -j4{{end}} knossos

  client-build-vs:
    cmds:
      - task: libarchive-build
      - task: libknossos-build
      - if [ ! -d build/client ]; then tool mkdir -p build/client; fi
      - cd build/client && cmake -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE={{.build}} ../../packages/client
      - cd build/client && cmake --build . --target knossos --config {{.build}}

  client-run:
    desc: Launches Knossos
    vars:
      KN_BIN: ./launcher/{{.build}}/knossos
      KN_BIN_OSX: ./launcher/{{.build}}/knossos.app/Contents/MacOS/knossos
      args: '{{default "" .args}}'
    dir: build/client
    cmds:
      - task: client-build
      - '{{if eq OS "darwin"}}{{.KN_BIN_OSX}}{{else}}{{.KN_BIN}}{{end}} {{.args}}'

  client-watch:
    deps:
      - client-ui-watch
      - task: client-run
        vars:
          args: '--url="http://localhost:9000/"'
